[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
idl-build = ["anchor-spl/idl-build"]

[programs.devnet]
vault = "Dq68yuxsdzLaC6Fmc6CCW4g3h6C5UaqVj3JrdQxKHQKi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id_1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
